application: tuneusserv
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /chat.py
  script: chat.py
- url: /session.py
  script: session.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"