application: tuneusserv
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /create_session.py
  script: create_session.app
- url: /get_session.py
  script: get_session.app
- url: /poll_chat.py
  script: poll_chat.app
- url: /add_video.py
  script: add_video.app
- url: /search_by.py
  script: search_by.app
- url: /check_queue.py
  script: check_queue.app
- url: /blob/.*
  script: upload_blob.app
- url: /update
  static_dir: update


libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "latest"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"